[project]
name = "sd-neighborhood-pulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-duckdb>=1.10.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
